### ISSUE TITLE
Bio impedância

### ISSUE THREAD

**Issue by JoseAntonioPires** [Diogonmt/DietFit#10]
Será registado (diariamente, semanalmente, quinzenalmente, etc.) pelo personal training ou pela nutricionista, o índice de massa corporal (IMC), massa gorda, massa não gorda, gordura visceral, água, peso, etc..
Estes dados devem ficar em histórico, podendo ser consultados pelo cliente, personal training e pela nutricionista.

**Comment by Diogonmt** [comment]
PBI=Criação do local onde personal training ou nutricionista registarão as várias informações relativas ao cliente (IMC, massa gorda, etc....);
CEA=Deverá existir um histórico para avaliar a evolução. A ser consultado tanto pelo cliente, personal training e nutricionista.
