### ISSUE TITLE
Consulta nutrição

### ISSUE THREAD

**Issue by JoseAntonioPires** [Diogonmt/DietFit#11]
Prioridade: 01

Irá existir uma primeira consulta de avaliação com a nutricionista e outras de acompanhamento que serão decididas conforme as necessidade de avaliação da nutricionista e da evolução do plano físico e nutricional.
É necessário registar as consultas e guardar o seu histórico, o personal training não pode ter acesso a esta informação. 
Por exemplo na primeira consulta a nutricionista realizara uma avaliação referente a saúde do cliente, histórico familiar, antecedentes pessoais, alergias, medicação, análises, intolerância alimentares, trânsito intestinal, hidratação, hábitos alimentares, tabágicos, etc..

**Comment by mlfazevedo** [comment]
Critérios de nutrição:
- Interface para registo das consultas por cliente.
- Guardar as consultas em histórico.
- Poder consultar o histórico das consultas.
- O PT (Personal Training) não pode ter acesso a essa informação.
