### ISSUE TITLE
Plano nutricional

### ISSUE THREAD

**Issue by JoseAntonioPires** [Diogonmt/DietFit#12]
Prioridade: 01

A nutricionista ira registar o plano nutricional personalizado para cada cliente e as respetivas alterações ao longo do tempo, como tal devera existir um histórico do mesmo, o personal training não tem necessidade de ter acesso a esta informação.

**Comment by mlfazevedo** [comment]
Critérios de aceitação:
- Interface para registo dos planos nutricionais por cliente.
- Guardar os planos nutricionais em histórico.
- Poder consultar os planos nutricionais em histórico.
- Cliente deverá ter acesso a essa informação e deverá receber um alerta quando o seu plano for alterado.
