### ISSUE TITLE
Plano físico

### ISSUE THREAD

**Issue by JoseAntonioPires** [Diogonmt/DietFit#8]
Introdução do mesmo pelo personal training, sendo que este deve estar disponível para visualização pela nutricionista e pelo cliente.
Quando existirem alterações no plano, antes deve ser guardado em histórico o anterior, sendo que a nutricionista deverá receber um alerta que foi alterado o plano físico do cliente X, para caso seja necessário alterar o plano nutricional.

**Comment by Diogonmt** [comment]
PBI=Existir um local onde se pode registar os planos físicos (Deverá ser visualizado pelo cliente e nutricionista);
CEA=Guardar em histórico os planos anteriores caso existam alterações do mesmo; Deverá ser enviado um alerta ao nutricionista desta mesmo alteração.

**Comment by mariobt** [comment]
Done. 
Alerta não efetuado devido a várias dificuldades da equipa de desenvolvimento
