### ISSUE TITLE
Registo atividade física

### ISSUE THREAD

**Issue by JoseAntonioPires** [Diogonmt/DietFit#9]
O personal training, regista a atividade física do cliente por cada seção, deverá ser guardado o histórico do mesmo. Deve estar disponível para visualização pelo personal training, nutricionista e pelo cliente.

**Comment by Diogonmt** [comment]
PBI=Criação de um registo de toda a atividade física por cada seção;
CEA=Deverá guardar em histórico todas as seções de atividade e deverá ser visível para nutricionista, personal trainer e cliente-
